### ISSUE TITLE
Port To Android

### ISSUE THREAD

**Issue by calebchris000** [Nabeelshar/Retro-Brick-Game#1]
## Hi @Nabeelshar ,

**Impressive job!** I spent some time playing the Tetris game and I must admit that it's a testament to your skill in creating games using pure JavaScript. Have you considered adapting it for React Native to develop an Android/iOS version?

**Comment by Nabeelshar** [comment]
https://play.google.com/store/apps/details?id=com.nab.brickgame9999in1
